server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
  #ssl:  #keytool -genkeypair -alias tomcat -keyalg RSA -keystore E:\tomcat.key 其中-alias是证书的别名,RSA是加密算法,-keystore后是输出证书的路径所在的证书路径
    #keystore: tomcat.key
    #key-store-type: JKS
    #key-alias: tomcat
    #    配置密码，就是在生成证书的时候输入的密码
    #key-store-password: bizehao
spring:
  mvc.throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.bzh.disciplineder.model